settings:
  coords: latlon
  medium: saltwater
  atm_pressure_hpa: 1013.25
  repeat_rate: 0.2
  range_rate: 1.0
  reply_timeout: 1.0
  pressure_rate: 1.0
  gps_fwd_rate: 1.0
  max_range_lag: 10.0
  max_gps_lag: 300.0
  lat0: 44.5
  lon0: -123.3

modems:
  123:
    mode: active
    rov: False
    serial_beacon: /dev/ttyBeacon
  101:
    mode: active
    rov: False
    serial_beacon: /dev/ttyBeacon
  202:
    mode: passive
    vessel: True
    x: 0.0
    y: 10.0
    lat: 44.56283
    lon: -123.27878
    z: -1.0
    broadcast_times: []
    serial_beacon: /dev/ttyBeacon
    serial_gps: /dev/ttyAMA0
    static: False
  203:
    mode: passive
    vessel: False
    x: 0.0
    y: 10.0
    lat: 44.56283
    lon: -123.27878
    z: -1.0
    broadcast_times: []
    serial_beacon: /dev/ttyBeacon
    serial_gps: /dev/ttyAMA0
    static: False
  204:
    mode: passive
    vessel: True
    x: 5.0
    y: -2.0
    lat: 44.56275
    lon: -123.27878
    z: -1.0
    broadcast_times: []
    serial_beacon: /dev/ttyBeacon
    serial_gps: /dev/ttyAMA0
    static: False
  205:
    mode: passive
    vessel: True
    x: -5.0
    y: -2.0
    lat: 44.56275
    lon: -123.27866
    z: -1.0
    broadcast_times: []
    serial_beacon: /dev/ttyBeacon
    serial_gps: /dev/ttyAMA0
    static: False
  106:
    mode: active
    rov: True
    serial_beacon: /dev/ttyBeacon
