settings:
  coords: local
  medium: saltwater
  sound_speed: 1500
  repeat_rate: 0.2
  range_rate: 1.0
  broadcast_rate: 3.0
  reply_timeout: 1.0
  randomize: 0.1
  pressure_rate: 1.0

modems:
  101:
    mode: active
    rov: True
    serial_beacon: /dev/ttyBeacon
  202:
    mode: passive
    x: 10
    y: -10
    z: 0
    serial_beacon: /dev/ttyBeacon
    serial_gps: /dev/ttyAMA0
    serial_pressure: /dev/ttyPressure
